FROM public.ecr.aws/amazonlinux/amazonlinux:2023
RUN dnf -y install e2fsprogs bash mdadm util-linux
COPY setup-runtime-storage ./
RUN chmod +x ./setup-runtime-storage
ENTRYPOINT ["sh", "setup-runtime-storage"]